### PR TITLE
Use BCP 47 Codes

### PR DESCRIPTION
**Pull request by radamson**
## Use BCP 47 Codes for Translations

[Browsers](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/language) and the [i18next library](https://www.i18next.com/how-to/faq#how-should-the-language-codes-be-formatted) used by this repository natively use BCP47 formatted codes.

This change significantly simplifies the implementation since mapping from BCP47 to custom codes is no longer necessary. i18next gracefully handles browsers configured with language subtags (e.g. `zh-cn`) and will default to the primary laguage tag (e.g. `zh`) if a specific region translation is not available.

This makes the code more maintainable and less brittle since fallbacks can automatically be performed and new translations can be added without code changes (or minimal code changes to add it as an option in the `Header`). It also fixes a few existing bugs caused by the current switch/case based approach.

I updated the `i18next` dependencies to access the [`i18next.resolvedLanguage`](https://www.i18next.com/overview/api#resolvedlanguage) method, which was introduced in v21.0.0. _(Note: I updated to the most recent `v21.5.0`)_. I also updated `i18next-http-backend` and `i18next-browser-languagedetector` as a matter of course.

_Note: This PR will require a complementary change to the backend API. The only changes required should be to use the updated language codes. You can see an example of how these codes were updated in the [WA API fork here](https://github.com/DOH-HTS-ADS/DigitalCovid19VaccineRecord-API/blob/89a2ec9835bc521d7d0331b269ca07de33916531/Application/_Common/Utils.cs#L289-L311)._
_https://github.com/StateOfCalifornia/DigitalCovid19VaccineRecord-API/pull/23 implements BCP 47 for the API repo._

Using resolved language preserves the current approach to reporting user language to the backend API - i.e. it reports the language translations it is displaying to the user. e.g. if a user has their browser configured to use `zh-cn`, it would report `zh` in the payload `POST /vaccineCredentialStatus` (see [here](https://github.com/dvci/DigitalCovid19VaccineRecord-UI/blob/52b3d587cd8afe28aa353e342aaaad9c343bbdd8/src/components/CovidCard.js#L115))

Translation mapping:

* `en` -> `en`
* `es` -> `es`
* `vi` -> `vi`
* `ae` -> `ar`
* `kr` -> `ko`
* `ph` -> `tl`
* `cn` -> `zh`
* `tw` -> `zh-TW`

## Bug Fixes

**Browsers configured to a Finnish [fi] language preference get Tagalog translation**

Steps to reproduce:

1. Set Browser langauge to Finnish [fi]
<details>
<summary>Example Firefox Screenshot</summary>

Screen Shot 2021-11-17 at 1 01 53 PM
</details>

2. Go to https://myvaccinerecord.cdph.ca.gov/ (Note: you may need to delete cookies. I was able to reproduce without deleting cookies on Firefox)

Culprit code:
https://github.com/StateOfCalifornia/DigitalCovid19VaccineRecord-UI/blob/fd25734d802ab1d1c17cf909dc32f3a3e48bccbb/src/i18n.js#L38-L39

**Browsers configured to Chinese [zh] language preference get English translation**

Steps to reproduce are same as above, but set to Chinese [zh] instead.

Culprit code:
https://github.com/StateOfCalifornia/DigitalCovid19VaccineRecord-UI/blob/fd25734d802ab1d1c17cf909dc32f3a3e48bccbb/src/i18n.js#L41-L43

### CODE REVIEW

**Comment by christopher-eddy-state-ca-gov** [comment]
Thank you for your submission. We are currently reviewing your pull request.

**Comment by christopher-eddy-state-ca-gov** [comment]
Thank you for your submission. We are currently reviewing your pull request.

**Comment by radamson** [comment]
Thanks! It looks like another PR just got merged which caused a merge conflict. I'm going to resolve those now and push again, but the code content won't change (all conflicts were in translation.json files which were not changed, only renamed)

**Comment by jon-grant-state-ca-gov** [comment]
Thank you for your submission. We reviewed and tested your pull request, and found 1 minor issue that was preventing the Traditional Chinese FAQ link from using the correct pathname.

In src\utils\faqLinkLanguage.js, one of the cases that the switch statement is looking for is 'zh-tw', but the browser will sometimes return 'zh-TW'.

Our suggested change would ensure that the language string is always lowercase:
image

We will merge this pull request as soon as this update has been made.

Thanks again!

**Comment by radamson** [comment]
@jon-grant-state-ca-gov implemented the fix using `toLowerCase()` I used a ternary operator instead of an `if/else` since the conditional is pretty simple and made the core functionality more readable. If you'd prefer I use the `if/else` instead let me know and I'll happily change it!

**Aside/Notes for Future Reference**
It looks like all browsers except Safari on iOS prior to 10.2 ([Reference MDN Docs](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/language)) should be returning the code with the regional subtag capitalized, but making this robust to handle any capitalization is a good idea since the [BCP47 RFC states](https://datatracker.ietf.org/doc/html/rfc5646#section-2.1.1) that language codes should be treated as case insenitive

**Comment by jon-grant-state-ca-gov** [comment]
Thank you for your submission. Your pull request is approved and has been merged :)

**Pull request merged**
