### PR TITLE
Provide Apple links on iPhone but not iPad

### PR DESCRIPTION
**Pull request by jmandel**
iPhone supports this integration but iPad does not

### CODE REVIEW

**Comment by jon-grant-state-ca-gov** [comment]
Thank you for your submission and bringing this to our attention. We reviewed your pull request and have found that iPod Touch also supports Apple Health & Wallet functionality. 

Please update your code to also match the user agent for iPod Touch.

**Comment by jmandel** [comment]
I don't have access to anything other than an iPad, so I'm not sure how to scope the check correctly. Wonder if @p2-apple may be able to suggest the right values?

**Comment by p2-apple** [comment]
The newer iPads will claim they are a Mac, so the user agent will be something like:
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15
```

Users can switch to their "mobile" user agent, which looks something like:
```
Mozilla/5.0 (iPad; CPU iPhone OS 15_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Mobile/15C44 Safari/604.1
```

And iPod touch will announce itself as something like:
```
Mozilla/5.0 (iPod; CPU iPhone OS 15_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Mobile/15C44 Safari/604.1
```

And an iPhone for completeness sake:
```
Mozilla/5.0 (iPhone; CPU iPhone OS 15_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Mobile/15C44 Safari/604.1
```

**Comment by jmandel** [comment]
Thanks -- I added a clause for `iPod`

**Comment by p2-apple** [comment]
`userAgent.match("iPhone")` will match for all of them, though, because they all have `CPU iPhone` in the agent.

**Comment by jmandel** [comment]
Right, good point -- so it was already correct before this last commit. I'll revert.

**Comment by jmandel** [comment]
OK, back to the initial proposal, which should work in iPhone and iPod, and should *not* display a link on iPad (in mobile or regular mode) or on Mac. Thanks @p2-apple.

**Comment by p2-apple** [comment]
iPads in mobile mode will have `CPU iPhone OS` so I think they will actually match. 😬

**Comment by jmandel** [comment]
Great! So we need one more negative check to exclude iPad.

**Comment by jmandel** [comment]
Like so?

**Comment by jon-grant-state-ca-gov** [comment]
We have updated the baseline and are testing your proposed changes.

**Comment by jon-grant-state-ca-gov** [comment]
Thank you for your submission. Your pull request is approved and has been merged.

**Pull request merged**
